package Assignment2.P2P;


/**
* Assignment2/P2P/fileInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server
* Tuesday, December 13, 2016 12:52:56 AM EST
*/

public final class fileInfo implements org.omg.CORBA.portable.IDLEntity
{
  public int fid = (int)0;
  public String name = null;
  public String path = null;
  public String address = null;
  public long size = (long)0;

  public fileInfo ()
  {
  } // ctor

  public fileInfo (int _fid, String _name, String _path, String _address, long _size)
  {
    fid = _fid;
    name = _name;
    path = _path;
    address = _address;
    size = _size;
  } // ctor

} // class fileInfo
