package Assignment2.P2P;


/**
* Assignment2/P2P/serverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server
* Friday, December 9, 2016 7:32:14 PM EST
*/

public interface serverOperations 
{
  boolean getFileLocation (int fid, org.omg.CORBA.StringHolder path, org.omg.CORBA.StringHolder clientAddress);
  void registerFile (String filename, String path, String clientAddress);
  boolean unRegisterFile (int fid);
} // interface serverOperations
