package Assignment2.P2P;

/**
* Assignment2/P2P/serverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server
* Tuesday, December 13, 2016 12:52:56 AM EST
*/

public final class serverHolder implements org.omg.CORBA.portable.Streamable
{
  public Assignment2.P2P.server value = null;

  public serverHolder ()
  {
  }

  public serverHolder (Assignment2.P2P.server initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Assignment2.P2P.serverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Assignment2.P2P.serverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Assignment2.P2P.serverHelper.type ();
  }

}
