package Assignment2.P2P;


/**
* Assignment2/P2P/server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server
* Friday, December 9, 2016 7:32:14 PM EST
*/

public interface server extends serverOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface server
