package Assignment2.P2P;


/**
* Assignment2/P2P/serverPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server
* Tuesday, December 13, 2016 12:52:56 AM EST
*/

public abstract class serverPOA extends org.omg.PortableServer.Servant
 implements Assignment2.P2P.serverOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getFileLocation", new java.lang.Integer (0));
    _methods.put ("registerFile", new java.lang.Integer (1));
    _methods.put ("unRegisterFile", new java.lang.Integer (2));
    _methods.put ("getAllSharedFiles", new java.lang.Integer (3));
    _methods.put ("searchFilesByName", new java.lang.Integer (4));
    _methods.put ("searchFilesByAddress", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Assignment2/P2P/server/getFileLocation
       {
         int fid = in.read_long ();
         org.omg.CORBA.StringHolder path = new org.omg.CORBA.StringHolder ();
         org.omg.CORBA.StringHolder clientAddress = new org.omg.CORBA.StringHolder ();
         boolean $result = false;
         $result = this.getFileLocation (fid, path, clientAddress);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_string (path.value);
         out.write_string (clientAddress.value);
         break;
       }

       case 1:  // Assignment2/P2P/server/registerFile
       {
         String filename = in.read_string ();
         String path = in.read_string ();
         String clientAddress = in.read_string ();
         long size = in.read_longlong ();
         this.registerFile (filename, path, clientAddress, size);
         out = $rh.createReply();
         break;
       }

       case 2:  // Assignment2/P2P/server/unRegisterFile
       {
         int fid = in.read_long ();
         boolean $result = false;
         $result = this.unRegisterFile (fid);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Assignment2/P2P/server/getAllSharedFiles
       {
         Assignment2.P2P.fileInfo $result[] = null;
         $result = this.getAllSharedFiles ();
         out = $rh.createReply();
         Assignment2.P2P.serverPackage.fileListHelper.write (out, $result);
         break;
       }

       case 4:  // Assignment2/P2P/server/searchFilesByName
       {
         String filename = in.read_string ();
         Assignment2.P2P.fileInfo $result[] = null;
         $result = this.searchFilesByName (filename);
         out = $rh.createReply();
         Assignment2.P2P.serverPackage.fileListHelper.write (out, $result);
         break;
       }

       case 5:  // Assignment2/P2P/server/searchFilesByAddress
       {
         String address = in.read_string ();
         Assignment2.P2P.fileInfo $result[] = null;
         $result = this.searchFilesByAddress (address);
         out = $rh.createReply();
         Assignment2.P2P.serverPackage.fileListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Assignment2/P2P/server:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public server _this() 
  {
    return serverHelper.narrow(
    super._this_object());
  }

  public server _this(org.omg.CORBA.ORB orb) 
  {
    return serverHelper.narrow(
    super._this_object(orb));
  }


} // class serverPOA
