package Assignment2.P2P;


/**
* Assignment2/P2P/serverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server
* Tuesday, December 13, 2016 12:52:56 AM EST
*/

public interface serverOperations 
{
  boolean getFileLocation (int fid, org.omg.CORBA.StringHolder path, org.omg.CORBA.StringHolder clientAddress);
  void registerFile (String filename, String path, String clientAddress, long size);
  boolean unRegisterFile (int fid);
  Assignment2.P2P.fileInfo[] getAllSharedFiles ();
  Assignment2.P2P.fileInfo[] searchFilesByName (String filename);
  Assignment2.P2P.fileInfo[] searchFilesByAddress (String address);
} // interface serverOperations
