package Assignment2.P2P.serverPackage;


/**
* Assignment2/P2P/serverPackage/fileListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server
* Tuesday, December 13, 2016 12:52:56 AM EST
*/

abstract public class fileListHelper
{
  private static String  _id = "IDL:Assignment2/P2P/server/fileList:1.0";

  public static void insert (org.omg.CORBA.Any a, Assignment2.P2P.fileInfo[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Assignment2.P2P.fileInfo[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Assignment2.P2P.fileInfoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Assignment2.P2P.serverPackage.fileListHelper.id (), "fileList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Assignment2.P2P.fileInfo[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Assignment2.P2P.fileInfo value[] = null;
    int _len0 = istream.read_long ();
    value = new Assignment2.P2P.fileInfo[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Assignment2.P2P.fileInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Assignment2.P2P.fileInfo[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Assignment2.P2P.fileInfoHelper.write (ostream, value[_i0]);
  }

}
